name: Build and Test

on:
  push:
    branches:
      - main  # Trigger on main branch commits

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'  # Adjust as needed

     # Step 3: Restore dependencies
    - name: Restore .NET Dependencies
      run: dotnet restore

    # Step 4: Build the solution
    - name: Build .NET Solution
      run: dotnet build --configuration Release --no-restore

    # Step 5: Run tests (optional, can be skipped if not needed)
    - name: Run Tests
      run: dotnet test --configuration Release --no-build


